### PR TITLE
implement speedups with rust and pyo3

### PR DESCRIPTION
**Pull request by davidism**
`pip install -e .` in a virtualenv should build `src/markupsafe/_rust_speedups.???.so`, assuming you have Rust installed.

`python bench.py` to run a benchmark comparing `escape("<strong>Hello, World!</strong>")` on the native and rust implementations. Currently native is ~6x faster. You can uncomment other parts of `bench.py` to run more benchmarks and also compare the C implementation.

`perf record -g python bench.py` says that ~2% of time is in calls to `replace`, while ~15% appears to be working with pointers. Not sure if that's pyo3 or something else, I don't really know Rust or perf well enough to diagnose it yet.

### CODE REVIEW

**Comment by itamarst** [comment]
From setuptools_rust docs:

```
debug (Optional[bool]) – Controls whether --debug or --release is passed to Cargo. If set to None (the default) then build type is automatic: inplace build will be a debug build, install and wheel builds will be release.
```

So you my be getting debug builds if installed with -e, and it'll be much slower than release build.

**Comment by davidism** [comment]
Doing `pip install .` instead of `pip install -e .` sped it up significantly. It's still slower by ~2x though.

**Comment by itamarst** [comment]
Things that jump out to me otherwise:

1. Lots and lots of calls back into Python in `escape()`, and ... that's slow. Maybe the import at least could be avoided?
2. `replace()` allocates a new string each time, which for large strings will be expensive. Maybe consider iterating character by character and doing a match on each character, and then joining the resulting iterator back into a new string.

**Comment by itamarst** [comment]
General comment: Python's string library is heavily optimized, and you're adding on an extra overhead of converting to and from UTF-8 in order to use Rust's string APIs.

**Comment by davidism** [comment]
The motivation here is that we already have these speedups written in C, and it seems like a good idea to write security-related code in Rust. I'd also like to use abi3 so that I don't have to build 49 wheels for each release, or new ones for new Python versions. I'm hoping pyo3's conversion overhead won't be a major factor in the end.

In C, the import is assigned to a static, so it's not done on each call. I'm not sure how to do that in Rust.

The C implementation does use `PyUnicode_KIND`, that's not in abi3 but I don't think it's needed since Rust will be iterating over UTF-8 characters only. The real trick is figuring out how to do all that clever memory stuff that C is doing, and I'm still pretty new to Rust :sweat_smile:

**Comment by davidism** [comment]
I went back and checked the benchmark on the C speedups. On Python 3.11, the speedups are actually slower for most strings, and only ~30us faster for the worst case benchmark (where most are nanoseconds). For Python 3.7, the results are only slightly better. :thinking:

**Comment by itamarst** [comment]
Yeah C is bad for security, no argument there :) This just seems like a very hard thing to optimize given Python's strings are actually pretty optimized and the core algorithm is tiny _and_ to call back into Python a lot.

One random idea, especially if C code isn't adding much: how about Cython where you're just compiling the pure Python implementation, with a few functions converted to cdef so you get inlining? Might lose some Python function call overhead that way, and apriori seems just as safe as the Python code, certainly safer than C doing stuff with pointers.

**Comment by itamarst** [comment]
This might be handy: https://lise-henry.github.io/articles/optimising_strings.html

> In this article, I'd like to explore how to process strings faster in Rust. I'll take the example of a function to escape the HTML <, > and & characters, starting from a naive implementation and trying to make it faster.

**Comment by itamarst** [comment]
So I guess "very hard" is maybe not true for the `escape_str()` part at least.

**Comment by itamarst** [comment]
Couple other random thoughts:

To prevent repeated imports in `escape()`, maybe use a static GILOnceCell to store the import (https://docs.rs/pyo3/latest/pyo3/once_cell/struct.GILOnceCell.html).

Adding this to `Cargo.toml` will add a little more speed usually, at the cost of longer compilation time (not a big deal for such a small amount of code):

```
[profile.release]
lto = "thin"
```

(Or try "fat").

**Comment by davidism** [comment]
Unfortunately,  I just don't have the time to learn Rust enough to get this right, right now. If anyone else wants to submit a Rust implementation, I'd be eager to review and merge it. Thanks @itamarst for helping out here last year.

**Pull request closed without merging**
