### PR TITLE
Add Python 3.9 support for 1.1.x

### PR DESCRIPTION
**Pull request by amureki**
As requested in https://github.com/pallets/markupsafe/pull/159#issuecomment-733452290
I am putting a separate PR (to be sure nothing forgotten/broken) with Python 3.9 support against 1.1.x branch.

Description:
- Adds Python 3.9 to GitHub actions and tox
- Replaces 3.8 with 3.9 for windows, mac, docs and linting builds
- Switch from Azure Pipelines to GitHub Actions to match with current main branch

### CODE REVIEW

**Comment by davidism** [comment]
Oh, I completely forgot we were using Azure Pipelines back then, that's not enabled anymore. Sorry this became so complicated. If you want, you can copy the build and test workflow files to here and remove the Azure config, or I can do that if it's getting to be too much.

**Comment by amureki** [comment]
@davidism no worries. :) We can switch to GitHub Actions right on this PR if you will, let me try that.

**Comment by amureki** [comment]
@davidism I switched to GitHub actions, checks passed, looks fine ✨. Is there anything else I might miss?

**Comment by johnthagen** [comment]
This would be great. Currently on Windows with 3.9, the `.tar.gz` sdist has to be downloaded and installed instead of a wheel.

**Pull request merged**
