### PR TITLE
Use PEP 393 new APIs

### PR DESCRIPTION
**Pull request by methane**
markupsafe doesn't support Python 3.2 anymore.
So just use new API at Python 3.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Small recommendation: Don't mix commits changing just whitespace with other commits

**Comment by methane** [comment]
Python 2:
```
before:
=============================================
Running benchmark for MarkupSafe
--------------------------------------------------------------------------------
basic                           100000 loops, best of 3: 5.01 usec per loop
largestring                     1000 loops, best of 3: 372 usec per loop
long_empty_string               10000 loops, best of 3: 81.4 usec per loop
long_suffix                     1000 loops, best of 3: 977 usec per loop
short_empty_string              100000 loops, best of 3: 4.57 usec per loop
--------------------------------------------------------------------------------

patched:
===============================================
Running benchmark for MarkupSafe
--------------------------------------------------------------------------------
basic                           100000 loops, best of 3: 2.02 usec per loop
largestring                     1000 loops, best of 3: 347 usec per loop
long_empty_string               10000 loops, best of 3: 58.2 usec per loop
long_suffix                     1000 loops, best of 3: 860 usec per loop
short_empty_string              1000000 loops, best of 3: 1.72 usec per loop
--------------------------------------------------------------------------------
```

**Comment by methane** [comment]
Python 3
```
before
==============================================
Running benchmark for MarkupSafe
--------------------------------------------------------------------------------
basic                           100000 loops, best of 3: 2.44 usec per loop
largestring                     1000 loops, best of 3: 262 usec per loop
long_empty_string               100000 loops, best of 3: 15.4 usec per loop
long_suffix                     1000 loops, best of 3: 505 usec per loop
short_empty_string              100000 loops, best of 3: 2.18 usec per loop
--------------------------------------------------------------------------------

patched
==============================================
Running benchmark for MarkupSafe
--------------------------------------------------------------------------------
basic                           100000 loops, best of 3: 2.26 usec per loop
largestring                     10000 loops, best of 3: 123 usec per loop
long_empty_string               100000 loops, best of 3: 13.5 usec per loop
long_suffix                     1000 loops, best of 3: 322 usec per loop
short_empty_string              100000 loops, best of 3: 2.07 usec per loop
--------------------------------------------------------------------------------
```

**Comment by methane** [comment]
```
before:

================================================================================
Running benchmark for MarkupSafe
--------------------------------------------------------------------------------
basic                           200000 loops, best of 5: 1.91 usec per loop
largestring                     2000 loops, best of 5: 199 usec per loop
long_empty_string               20000 loops, best of 5: 15.9 usec per loop
long_suffix                     1000 loops, best of 5: 386 usec per loop
short_empty_string              200000 loops, best of 5: 1.66 usec per loop
--------------------------------------------------------------------------------

patched:

================================================================================
Running benchmark for MarkupSafe
--------------------------------------------------------------------------------
basic                           200000 loops, best of 5: 1.34 usec per loop
largestring                     2000 loops, best of 5: 111 usec per loop
long_empty_string               20000 loops, best of 5: 10.2 usec per loop
long_suffix                     1000 loops, best of 5: 234 usec per loop
short_empty_string              200000 loops, best of 5: 1.21 usec per loop
--------------------------------------------------------------------------------
```

**Comment by davidism** [comment]
We no longer support 2.6 and 3.3 either. Would that affect this code (probably make it simpler)?

**Comment by methane** [comment]
I don't think so.

On the other hand, I can remove Python 2 specific code and share same logic (GET_DELAT and DO_ESCAPE macro).

**Comment by davidism** [comment]
@methane I'm not very familiar with C / the C-API. If you have some time, would you mind checking #74 just so I know it makes sense?

**Comment by methane** [comment]
Python 2.7.13

```
before:
================================================================================
Running benchmark for MarkupSafe
--------------------------------------------------------------------------------
basic                           1000000 loops, best of 3: 1.79 usec per loop
largestring                     1000 loops, best of 3: 261 usec per loop
long_empty_string               10000 loops, best of 3: 42.7 usec per loop
long_suffix                     1000 loops, best of 3: 630 usec per loop
short_empty_string              1000000 loops, best of 3: 1.68 usec per loop
--------------------------------------------------------------------------------

after:
================================================================================
Running benchmark for MarkupSafe
--------------------------------------------------------------------------------
basic                           1000000 loops, best of 3: 1.79 usec per loop
largestring                     1000 loops, best of 3: 286 usec per loop
long_empty_string               10000 loops, best of 3: 38.4 usec per loop
long_suffix                     1000 loops, best of 3: 726 usec per loop
short_empty_string              1000000 loops, best of 3: 1.46 usec per loop
--------------------------------------------------------------------------------
```

Hmm, 379d0d0 makes escaping little slower on PY2.7.

**Comment by davidism** [comment]
I'm fine with reverting it if it makes it faster.

**Comment by methane** [comment]
I removed last commit.
We can remove PY2 only code after PY2 EOL anyway.  So keeping some PY2 only code for few years is not big problem.

**Comment by ThiefMaster** [comment]
> We can remove PY2 only code after PY2 EOL anywa

More like "only after EOL being dropped by all major distributions, and not being relevant anymore" ;)

**Comment by methane** [comment]
"after" didn't mean "right after".
I don't care when you drop PY2 support.

(FYI, Django 2.0 has significant performance gain from dropping PY2 support. 😉 )

**Comment by davidism** [comment]
Rebased to master. Converted to pytest.

**Comment by davidism** [comment]
Thanks for working on this!

**Pull request merged**
